---
- name: Install Paint.NET on Windows
  hosts: windows
  become: yes
  tasks:

    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Paint.NET
      win_chocolatey:
        name: paint.net
        state: present
