---
- name: Run Docker installation script from GitHub
  hosts: all
  become: yes  # Run as sudo
  become_user: root
  tasks:
    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Download and execute Docker install script with progress
      shell: wget --show-progress -qO- https://raw.githubusercontent.com/Rvssian-SEZ/Semaphore/main/install_docker.sh | bash
      args:
        executable: /bin/bash
      register: install_output
      failed_when: install_output.rc != 0

    - name: Add user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Display installation progress
      debug:
        msg: "{{ install_output.stdout_lines | default('No output captured') }}"

    - name: Confirm Docker installation completion
      debug:
        msg: "Docker installation completed successfully. Please log out and log back in for group changes to take effect."

- name: Add all sudoers to the Docker group
  hosts: all
  become: yes  # Run tasks as root
  tasks:
    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Get list of sudo users
      command: getent group sudo
      register: sudo_users
      changed_when: false

    - name: Extract users from sudo group
      set_fact:
        sudo_users_list: "{{ sudo_users.stdout.split(':')[-1].split(',') }}"

    - name: Add sudo users to the Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ sudo_users_list }}"
      when: sudo_users_list | length > 0

    - name: Inform users to log out and back in
      debug:
        msg: "All sudoers have been added to the Docker group. Please log out and log back in for changes to take effect."
