---
- name: Run Docker installation script from GitHub
  hosts: all
  become: yes  # Run as sudo
  become_user: root
  tasks:
    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Download and execute Docker install script with progress
      shell: wget --show-progress -qO- https://raw.githubusercontent.com/Rvssian-SEZ/Semaphore/main/install_docker.sh | bash
      args:
        executable: /bin/bash
      register: install_output
      failed_when: install_output.rc != 0

    - name: Add user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Display installation progress
      debug:
        msg: "{{ install_output.stdout_lines | default('No output captured') }}"

    - name: Confirm Docker installation completion
      debug:
        msg: "Docker installation completed successfully. Please log out and log back in for group changes to take effect."
