---
- name: Run Docker installation script from GitHub
  hosts: all  # Change this to the target group or host
  become: yes  # Run as sudo
  become_user: root
  tasks:
    - name: Download and execute Docker install script
      shell: https://raw.githubusercontent.com/Rvssian-SEZ/Semaphore/refs/heads/main/install_docker.sh | bash
      args:
        executable: /bin/bash
      register: install_output
      failed_when: install_output.rc != 0

    - name: Display installation output
      debug:
        msg: "Docker installation completed successfully."
