---
- name: Execute lsb_release -a on remote hosts
  hosts: all  # Change this to the target group or host
  gather_facts: no
  tasks:
    - name: Run lsb_release -a command
      command: lsb_release -a
      register: lsb_output
      ignore_errors: yes  # Avoid playbook failure if command is unavailable

    - name: Display command output
      debug:
        msg: "{{ lsb_output.stdout_lines | join('\n') }}"
