---
- name: Execute lsb_release -a on remote hosts
  hosts: all  # Change this to the target group or host
  gather_facts: no
  tasks:
    - name: Run lsb_release -a command
      command: lsb_release -a
