- name: Ensure lsb_release is installed on all hosts
  hosts: all
  become: true
  tasks:
    - name: Ensure lsb_release is installed (Debian/Ubuntu)
      apt:
        name: lsb-release
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure lsb_release is installed (RedHat/CentOS/Rocky)
      yum:
        name: redhat-lsb-core
        state: present
      when: ansible_os_family == "RedHat"
