---
- name: Install VLC and display progress
  hosts: all  # Change this to the target group or host
  become: yes  # Run as sudo
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      register: update_output

    - name: Display update progress
      debug:
        msg: "Package cache updated successfully"

    - name: Install VLC
      apt:
        name: vlc
        state: present
      register: install_output

    - name: Display installation progress
      debug:
        msg: "VLC installation status: {{ 'changed' if install_output.changed else 'already installed' }}"
